name: Trigger auto deployment for pipboy

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ v5 ]
    paths:
    - '**'
    - '.github/workflows/pipboy-AutoDeployTrigger-0884828b-5ff6-4107-873d-4aa5c7e672dc.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PIPBOY_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: pipboy.azurecr.io
          registryUsername: ${{ secrets.PIPBOY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PIPBOY_REGISTRY_PASSWORD }}
          containerAppName: pipboy
          resourceGroup: CordDis
          imageToBuild: pipboy.azurecr.io/pipboy:${{ github.sha }}
          

     

